### ISSUE TITLE
State model short term optimizations

### ISSUE THREAD

**Issue by vogel76** [steemit/steem#1923]
There is a need to reduce execution time of reindex action and memory footprint of produced state object model.
Tasks below are defined according to research and analysis done before,

- [x] Implement compilation time switching between boost::interprocess allocator and standard memory allocator (#1984)
- [x] Eliminate significant overhead during follow & tags plugin data removing (bad query for next iterator value) (#1947)
- [x] Reuse feed objects in the follow-plugin data model instead of removing them and creating new one (#1948)
- [x] Avoid create & immediate remove of account history object when prune is enabled. (#1949)
- [x] Redesign account history object structure and hold list of operations per given account instead of multiple account_history_object pairing account and the operation (#1949)
- [x] Eliminate unused indices created by follow_plugin data structures: `feed_index`: `by_account`, `by_old_feed`, `blog_index`. `blog_index`: `by_old_blog`. `reputation_index`: `by_reputation`. `follow_count_index`: `by_followers`, `by_following` (#1950)
- [x] Extend reindex-process benchmark data collector by report containing info about built datastructures (#1985)
- [ ] Extend reindex-process benchmark by collection statistical and execution time informations related to operations processed for each visited block (#1996)
- [ ] Implement automatic data serializer, to automatically generate code doing static serialization (no reflect) #1932
- [ ] Implement  dedicated persistent storage of state object model, be able to load data on demand (#1987).
- [ ] Logical split of steemd process to separate process doing pure blochain sync (p2p) and another one, doing state sync basing on previously synced local blockchain storage. Issue #1931
- [ ] Review all existing indices to check for obsolete ones and potentially replaceable by reverse_iterator usage (especially look for indices prefixed with `by_old`). (#1951)
- [ ] Implement string pooling to reduce memory allocation of stored texts. #1595 
- [ ] Review unique index usage - there shall be left only these unique indices where such uniqueness is defined by business logic. Correct item ordering shall be still still preserved by superfluous storing 'id' of the object together with actual key. Removing unneeded uniqueness can allow reduction of key definition which now must match to enforced uniqueness.
- [ ] Allow automatic API test generation to allow fast creation of initial API testsuite (#1986)

**Comment by mvandeberg** [comment]
Individual issues will be prioritized accordingly.

Closing.
