### ISSUE TITLE
Enhance RocksDB prototype by support for data undo when database returns back from fork.

### ISSUE THREAD

**Issue by vogel76** [steemit/steem#2040]
- [x] Implement unit tests to show cases when database enters a fork (also recursively) and next returns back from it. Initial tests can be done just for undo state as described: #2086
- [ ] Implement an abstract representation of undo_state to allow usage of its different implementations at the same time #2087
- [ ] Implement notification sent by chain::database that it enters a fork and returns back from fork #2088.

Data in storage must be correctly restored to the state they appeared before database forked. All new items shall be removed, deleted ones restored and changed updated to their previous values.

**Comment by sneak** [comment]
Is this really the approach we want to take?  Why not keep the RocksDB implementation simple, and only use it to store data behind last_irreversible?

**Comment by mvandeberg** [comment]
I am in agreement on this.

The model that Theoreticalbts presented in 1987 clearly shows the abstractions that we are working with in our database.

A big benefit of the way we handle state is that no business logic needs to be fork aware.

Use Chainbase (memory mapped or in memory) for reversible state and RocksDB for irreversible is a model that I can easily see working long term and requires re-implementing less of our foundational logic. I would like this model to be used for the Account History RocksDB plugin.

**Comment by vogel76** [comment]
When we will have separated storages holding state data (the RocksDB for state evaluated up to irreversible block, and 2nd for not yet fully confirmed - potentially undoable - data in memory) how do you want to support data access interface, which will need to join these 2 storages and behave as single one ? As long as such join will be needed (if not, please explain) this implementation looks to me much more complex than storage basing on single solution.
