### ISSUE TITLE
Design and implement boost::multi_index replacement basing on RocksDB storage 

### ISSUE THREAD

**Issue by vogel76** [steemit/steem#2041]
Designed class must emulate boost::multi_index container interface to allow simple and iterative replacement of each defined index, without a need to do massive changes in other code using these indices.

Work can be split into following phases:

- [x] Create an unit test covering the container use cases #2288 
- [x] Implement custom iterators be responsible for providing data from one or more concatenated sources #2289
- [ ] Implement pure `boost::multi_index::multi_index_container` adapter class, which can have specified different (potentially multiple) data sources #2290
- [x] Implement StorageConfigurationManager class providing functionality described in the [architecture document](https://docs.google.com/document/d/1LPScSMURj5x4hQumkKSLkap__BDnyLpOGMKqWVnBo3c/edit?usp=sharing) #2291
- [ ] Implement PersistentStorage class providing functionality described in in the [architecture document](https://docs.google.com/document/d/1LPScSMURj5x4hQumkKSLkap__BDnyLpOGMKqWVnBo3c/edit?usp=sharing) #2292
- [ ] Implement a data source providing objects stored in the RocksDB database #2293

**Comment by vogel76** [comment]
This task is blocked until #1984 will be merged to develop to have codebase for further work.

**Comment by youkaicountry** [comment]
Blocked by #2158

**Comment by youkaicountry** [comment]
An additional requirement while implementing this:
For any index that is non-unique, an iterator should not be allowed to be returned.
