### ISSUE TITLE
Metaissue: to-do for serving prod AH reads out of non-steemd

### ISSUE THREAD

**Issue by sneak** [steemit/steem#2171]
Issue created in `steem` repo because irony.

- [ ] https://github.com/steemit/steem/issues/2099 - exfiltration of vops from steemd
    - this could also be accomplished by using current AH plugin with only vops whitelisted
- [ ] https://github.com/steemit/sbds/issues/100 - sbds metaissue for virtual ops indexing
- [ ] FIXME - steem-js changes
- [ ] https://github.com/steemit/condenser/issues/2605 - condenser changes

**Comment by mvandeberg** [comment]
Closing as out of date
