### ISSUE TITLE
User participating in SMT ICO

### ISSUE THREAD

**Issue by youkaicountry** [steemit/steem#2730]
As a user interested in a token, I want to be able to contribute to the ICO, so that the user owns interest in the SMT.

**Note:**
Entails:
smt_contribute_operation
contribution_phase

```c++
smt_contribute_operation
{
   account_name_type contributor;
   account_symbol_type symbol;
   uint32_t contribution_id; // (contributor, symbol, contribution_id) must be a unique tuple
   asset amount;

   extensions_type extensions;
};
```
**AC:**
1. This creates a contribution object that needs to track individual contributions on an SMT during the ICO phase. These contributions need to be sorted chronologically. `by_id` is sufficient.
2. Only STEEM can be contributed.
3. User must possess the STEEM to be contributed.
4. Only valid during ICO phase.
5. If the contribution would cause the total contributions to pass a revealed hard cap, the ICO phase is completed and the SMT is now waiting for launch.
6. Refactor ICO fields from `smt_token_object` in to a secondary token object that contains fields specific to ICO phase that can be removed after the ICO succeeds or fails.
7. When returning a token object in an API, add an optional subfield that contains the ICO specific object if the SMT is in the ICO phase.

**Tasks:**
- [x] Update `smt_token_object` API calls to return optional secondary ICO fields.
- [x] Validation/testing of `smt_contribute_operation`.
- [x] Evaluation/testing of `smt_contribute_operation`.
- [x] Refactor ICO fields into secondary object.
- [x] Add API calls to retrieve ICO Contribution Objects
- [ ] Update SMT Whitepaper
