### ISSUE TITLE
Delegation Pools

### ISSUE THREAD

**Issue by youkaicountry** [steemit/steem#2761]
- [x] #2696 Implement Delegation Pool Objects
- [X] #2697 Delegation Pool Per-User Consumption
- [X] #2698 SMT Delegation Pools
- [X] #2705 Users Delegate to Multiple Pools

- [ ] General Documentation
- [X] Unit Tests
- [ ] API changes documented
