### ISSUE TITLE
SMT Setup Cleanup

### ISSUE THREAD

**Issue by mvandeberg** [steemit/steem#3378]
- [X] Rename generation start/end times to contribute. (#3381)
- [X] Remove redundant precision in smt_setup_operation.(#3381)
- [X] Remove smt_base_operation and smt_executor_operation. (#3381)
